### ISSUE TITLE
Verlinkung der Pinterest-Buttons korrigieren

### ISSUE THREAD

**Issue by Art4** [Art4/pinthis-child#1]
Der Pinterest-Button sollte direkt zur Erstellung eines Posts bei Pinterest führen.

url: Post-Url
media: Url zum Beitragsbild
description: Post-Content

Siehe: https://stackoverflow.com/questions/10690019/link-to-pin-it-on-pinterest-without-generating-a-button

**Comment by weigandtstudios** [comment]
Wie schaut es hier aus? Muss ich dir irgendwelche extra info geben?
