### ISSUE TITLE
Uncategorized entfernen

### ISSUE THREAD

**Issue by weigandtstudios** [Art4/pinthis-child#2]
Bitte die Kategorie "Uncategorized" entfernen

![screen shot 2015-08-22 at 7 03 43 pm](https://cloud.githubusercontent.com/assets/13957127/9459199/693dfff0-4abe-11e5-98bb-7c267b2cab16.png)

**Comment by weigandtstudios** [comment]
Hat sich erledigt, konnte sie zwar nicht loswerden habe es aber umgenannt  und dann ging es schon :+1:

**Comment by Art4** [comment]
Das ist die Standard-Kategorie für deine Beiträge und kann nicht gelöscht werden. Die Standardkategorie für Beiträge kannst du in _Einstellungen_ -> _Schreiben_ verändern.
