### ISSUE TITLE
Den Subbutton nach rechts verschieben

### ISSUE THREAD

**Issue by weigandtstudios** [Art4/pinthis-child#3]
Ich hoffe das Bild sagt was aus, ich würde gerne die Unterseite nur auftauchen lassen wenn man die Kategorie anwählt.

![screen shot 2015-08-22 at 7 03 55 pm](https://cloud.githubusercontent.com/assets/13957127/9459255/03fd2160-4abf-11e5-9477-64dc68b2fcbe.png)

**Comment by Art4** [comment]
Das würde ich nicht empfehlen. Das würde das responsive Design kaputt machen. Und es ist einiges an Arbeit. :grin:
