### ISSUE TITLE
Verlinkung von Author name mit Biography

### ISSUE THREAD

**Issue by weigandtstudios** [Art4/pinthis-child#6]
![screen shot 2016-02-03 at 10 57 51 pm](https://cloud.githubusercontent.com/assets/13957127/12806274/1613f0c8-caca-11e5-9ca1-91de13595382.png)

Kann man den Namen des Authoren mit der Biography irgendwie verlinken? Wenn das geht dann waere da super....

**Comment by Art4** [comment]
@weigandtstudios Kannst du mir ein Beispiel geben? Welcher Teil in dem Screenshot soll mit welcher (Beispiel-)Url verlinkt sein?

**Comment by weigandtstudios** [comment]
![screen shot 2016-02-04 at 8 36 15 am](https://cloud.githubusercontent.com/assets/13957127/12818047/bf873084-cb1a-11e5-9067-c96bd9637d0c.png)


Das ist momentan die einzige biography die ich online habe
http://www.quoteterest.com/the-life-and-work-of-alfred-stieglitz-a-short-biography/

**Comment by Art4** [comment]
Mir fällt spontan ein, dass man die Verlinkung direkt beim Quote Author eintragen kann, zB. so:

`<a href="http://www.quoteterest.com/the-life-and-work-of-alfred-stieglitz-a-short-biography/">Alfred Stieglitz</a>`

**Comment by weigandtstudios** [comment]
Ja das funkioniert, natuerlich waere mir eine automatisierte Loesung lieber aber ich mach das dann so.. Danke
