### ISSUE TITLE
Neachster Artikel in der selben Kategorie

### ISSUE THREAD

**Issue by weigandtstudios** [Art4/pinthis-child#7]
![screen shot 2016-02-03 at 11 03 33 pm](https://cloud.githubusercontent.com/assets/13957127/12806301/645bfc8a-caca-11e5-9f72-9f3df68c449f.png)
Kann man den Next post darauf beschreanken das er immer nur den neachsten post in der kategorie anzeigt anstelle von der reigenfolge des publizier datums aller kategorien?

**Comment by Art4** [comment]
Ja, das ist möglich. Laut Code müsste es dafür schon eine Einstellung in den Theme-Optionen geben.

**Comment by weigandtstudios** [comment]
Hatte danach gegoogelt aber da waren nur plugins zu verfuegung die schon seit  2 jahren nicht upgedated wurden.. von einstellungen habe ich nichts gelesen.. weisst du wo?

**Comment by Art4** [comment]
Habe grade nachgesehen: `PBPanel` -> `Main` -> `Links To Posts In Same Categoy`
