### ISSUE TITLE
Vorschau Bild komplett als quadtrat anzeigen lassen

### ISSUE THREAD

**Issue by weigandtstudios** [Art4/pinthis-child#8]
![screen shot 2016-02-08 at 6 22 00 am](https://cloud.githubusercontent.com/assets/13957127/12885568/88e9354e-ce2c-11e5-9987-58d076d328c5.png)

Kann man das Vorschau Bild bei den related posts als quadrat anzeigen lassen? Alle Bilder sind viereckig... dieses related post thing ist ein Jetpack feature.

**Comment by Art4** [comment]
Das Vorschaubild wird von Jetpack automatisch auf 350x200px beschnitten. Viel machen kann man da nicht.

Siehe den letzten Absatz auf https://jetpack.me/support/related-posts/

> **2**. Thumbnails are resized and cropped automatically using Photon to be 350px wide by 200px tall (1.75:1 ratio) to allow for a consistent visual display. Since this is done automatically, there’s no way to fine-tune where the image is cropped

Ich kann mir vorstellen, dass man da irgendwo einstellen kann, auf welche Maße das Vorschaubild beschnitten werden soll. Aber ich kenne mich mit Jetpack nicht aus.

**Comment by Art4** [comment]
Ok, ich habe was gefunden. Jetpack erlaubt die Manipulation der Maße über einen Filter, siehe https://github.com/Automattic/jetpack/blob/eddb11711a206a5c1de14b92e958c379670cb099/modules/related-posts/jetpack-related-posts.php#L888

Man kann also einen eigenen Filter schreiben, der die Abmaße anpasst. Wenn ich das richtig gesehen habe, reicht dir auch ein Thumbnail von 300x300px, wodurch du etwas Trafic sparen kannst.

```php
function ptc_jetpack_relatedposts_filter_thumbnail_size($thumbnail_size)
{
	$thumbnail_size['width'] = 300;
	$thumbnail_size['height'] = 300;
	return $thumbnail_size;
}
add_filter('jetpack_relatedposts_filter_thumbnail_size', 'ptc_jetpack_relatedposts_filter_thumbnail_size');
```

Kannst du den Code oben mal in deine `functions.php` einfügen und dann gucken, ob es funktioniert? Wenn ja, dann bau ich dir das richtig ein und erstelle ein neues Release.

**Comment by weigandtstudios** [comment]
Japp, habs in die function.php von der childtheme implementiert und es funktioniert... :)

**Comment by Art4** [comment]
Ok, danke. :+1:
